import Foundation

struct Country {
  let code: String?
}

extension Country {
  static let afghanistan: Country = "AFG"
  static let unitedArabEmirates: Country = "AE"
  static let antiguaAndBarbuda: Country = "AG"
  static let anguilla: Country = "AI"
  static let albania: Country = "AL"
  static let armenia: Country = "AM"
  static let angola: Country = "AO"
  static let argentina: Country = "AR"
  static let austria: Country = "AT"
  static let australia: Country = "AU"
  static let azerbaijan: Country = "AZ"
  static let barbados: Country = "BB"
  static let belgium: Country = "BE"
  static let bosniaAndHerzegovina: Country = "BIH"
  static let burkinaFaso: Country = "BF"
  static let bulgaria: Country = "BG"
  static let bahrain: Country = "BH"
  static let benin: Country = "BJ"
  static let bermuda: Country = "BM"
  static let brunei: Country = "BN"
  static let bolivia: Country = "BO"
  static let brazil: Country = "BR"
  static let bahamas: Country = "BS"
  static let bhutan: Country = "BT"
  static let botswana: Country = "BW"
  static let belarus: Country = "BY"
  static let belize: Country = "BZ"
  static let cameroon: Country = "CMR"
  static let canada: Country = "CA"
  static let congoRepublic: Country = "CG"
  static let switzerland: Country = "CH"
  static let coteDIvoire: Country = "CIV"
  static let chile: Country = "CL"
  static let china: Country = "CN"
  static let colombia: Country = "CO"
  static let congoDemocraticRepublic: Country = "COD"
  static let costaRica: Country = "CR"
  static let capeVerde: Country = "CV"
  static let cyprus: Country = "CY"
  static let czechRepublic: Country = "CZ"
  static let germany: Country = "DE"
  static let denmark: Country = "DK"
  static let dominica: Country = "DM"
  static let dominicanRepublic: Country = "DO"
  static let algeria: Country = "DZ"
  static let ecuador: Country = "EC"
  static let estonia: Country = "EE"
  static let egypt: Country = "EG"
  static let spain: Country = "ES"
  static let finland: Country = "FI"
  static let fiji: Country = "FJ"
  static let micronesia: Country = "FM"
  static let france: Country = "FR"
  static let gabon: Country = "GAB"
  static let unitedKingdom: Country = "GB"
  static let grenada: Country = "GD"
  static let georgia: Country = "GEO"
  static let ghana: Country = "GH"
  static let gambia: Country = "GM"
  static let greece: Country = "GR"
  static let guatemala: Country = "GT"
  static let guineaBissau: Country = "GW"
  static let guyana: Country = "GY"
  static let hongKong: Country = "HK"
  static let honduras: Country = "HN"
  static let croatia: Country = "HR"
  static let hungary: Country = "HU"
  static let indonesia: Country = "ID"
  static let ireland: Country = "IE"
  static let israel: Country = "IL"
  static let india: Country = "IN"
  static let iraq: Country = "IRQ"
  static let iceland: Country = "IS"
  static let italy: Country = "IT"
  static let jamaica: Country = "JM"
  static let jordan: Country = "JO"
  static let japan: Country = "JP"
  static let kenya: Country = "KE"
  static let kyrgyzstan: Country = "KG"
  static let cambodia: Country = "KH"
  static let stKittsAndNevis: Country = "KN"
  static let korea: Country = "KR"
  static let kuwait: Country = "KW"
  static let caymanIslands: Country = "KY"
  static let kazakhstan: Country = "KZ"
  static let laos: Country = "LA"
  static let lebanon: Country = "LB"
  static let libya: Country = "LBY"
  static let stLucia: Country = "LC"
  static let sriLanka: Country = "LK"
  static let liberia: Country = "LR"
  static let lithuania: Country = "LT"
  static let luxembourg: Country = "LU"
  static let latvia: Country = "LV"
  static let morocco: Country = "MAR"
  static let moldova: Country = "MD"
  static let maldives: Country = "MDV"
  static let madagascar: Country = "MG"
  static let northMacedonia: Country = "MK"
  static let mali: Country = "ML"
  static let myanmar: Country = "MMR"
  static let mongolia: Country = "MN"
  static let montenegro: Country = "MNE"
  static let macau: Country = "MO"
  static let mauritania: Country = "MR"
  static let montserrat: Country = "MS"
  static let malta: Country = "MT"
  static let mauritius: Country = "MU"
  static let malawi: Country = "MW"
  static let mexico: Country = "MX"
  static let malaysia: Country = "MY"
  static let mozambique: Country = "MZ"
  static let namibia: Country = "NA"
  static let niger: Country = "NE"
  static let nigeria: Country = "NG"
  static let nicaragua: Country = "NI"
  static let netherlands: Country = "NL"
  static let norway: Country = "NO"
  static let nepal: Country = "NP"
  static let nauru: Country = "NRU"
  static let newZealand: Country = "NZ"
  static let oman: Country = "OM"
  static let panama: Country = "PA"
  static let peru: Country = "PE"
  static let papuaNewGuinea: Country = "PG"
  static let philippines: Country = "PH"
  static let pakistan: Country = "PK"
  static let poland: Country = "PL"
  static let portugal: Country = "PT"
  static let palau: Country = "PW"
  static let paraguay: Country = "PY"
  static let qatar: Country = "QA"
  static let romania: Country = "RO"
  static let russia: Country = "RU"
  static let rwanda: Country = "RWA"
  static let saudiArabia: Country = "SA"
  static let solomonIslands: Country = "SB"
  static let seychelles: Country = "SC"
  static let sweden: Country = "SE"
  static let singapore: Country = "SG"
  static let slovenia: Country = "SI"
  static let slovakia: Country = "SK"
  static let sierraLeone: Country = "SL"
  static let senegal: Country = "SN"
  static let suriname: Country = "SR"
  static let serbia: Country = "SRB"
  static let saoTomeAndPrincipe: Country = "ST"
  static let elSalvador: Country = "SV"
  static let swaziland: Country = "SZ"
  static let turksAndCaicosIslands: Country = "TC"
  static let chad: Country = "TD"
  static let thailand: Country = "TH"
  static let tajikistan: Country = "TJ"
  static let turkmenistan: Country = "TM"
  static let tunisia: Country = "TN"
  static let tonga: Country = "TON"
  static let turkey: Country = "TR"
  static let trinidadAndTobago: Country = "TT"
  static let taiwan: Country = "TW"
  static let tanzania: Country = "TZ"
  static let ukraine: Country = "UA"
  static let uganda: Country = "UG"
  static let unitedStates: Country = "US"
  static let uruguay: Country = "UY"
  static let uzbekistan: Country = "UZ"
  static let stVincentAndTheGrenadines: Country = "VC"
  static let venezuela: Country = "VE"
  static let britishVirginIslands: Country = "VG"
  static let vietnam: Country = "VN"
  static let vanuatu: Country = "VUT"
  static let kosovo: Country = "XKS"
  static let yemen: Country = "YE"
  static let southAfrica: Country = "ZA"
  static let zambia: Country = "ZMB"
  static let zimbabwe: Country = "ZW"
}

extension Country: Equatable {
  static func == (lhs: Country, rhs: Country) -> Bool {
    return lhs.code?.uppercased() == rhs.code?.uppercased()
  }
}

extension Country: ExpressibleByStringLiteral {
  init(stringLiteral value: StringLiteralType) {
    self.init(code: value)
  }
}
